'use strict';

// The assembly pane: cc1 -S for the file in the other half of the window.
//
// This is a virtual document rather than a written file. Nothing lands in the
// user's directory, the pane cannot be edited into disagreeing with its
// source, and the content is regenerated on demand - which is what lets the
// same pane answer for a different target the moment the target changes.
//
// The tab keeps the extension it was opened with. Switching from MASM to the
// GNU spelling therefore leaves a pane called .asm showing .s content; the
// grammar colours both, so this costs a slightly wrong label and nothing else.

const fs = require('fs');
const path = require('path');
const vscode = require('vscode');
const cc1 = require('./cc1');

const SCHEME = 'cc1-asm';

class AssemblyProvider {
  constructor(output) {
    this.output = output;
    this.emitter = new vscode.EventEmitter();
    this.onDidChange = this.emitter.event;
    this.sources = new Map(); // uri string -> source file path
  }

  // The pane's address. The source path rides in the query so the provider can
  // recover it; the visible part is just a filename, because that is what the
  // tab shows.
  uriFor(sourcePath) {
    const base = path.basename(sourcePath, path.extname(sourcePath));
    const uri = vscode.Uri.parse(
      SCHEME + ':/' + encodeURIComponent(base + cc1.assemblySuffix()) +
      '?' + encodeURIComponent(sourcePath)
    );
    this.sources.set(uri.toString(), sourcePath);
    return uri;
  }

  // Called when the source is saved or edited. Only fires for panes that are
  // actually open on that source, so an untouched pane costs nothing.
  refreshFor(sourcePath) {
    for (const [key, src] of this.sources) {
      if (src === sourcePath) this.emitter.fire(vscode.Uri.parse(key));
    }
  }

  // Called when the target changes, since every pane's answer changed at once.
  refreshAll() {
    for (const key of this.sources.keys()) this.emitter.fire(vscode.Uri.parse(key));
  }

  // Called when a pane's document is closed, so the map holds only open panes
  // rather than every pane there has ever been.
  forget(uri) {
    this.sources.delete(uri.toString());
  }

  async provideTextDocumentContent(uri) {
    const source = this.sources.get(uri.toString()) || decodeURIComponent(uri.query);
    const comment = cc1.assemblySuffix() === '.asm' ? '; ' : '# ';
    const exe = cc1.findCompiler(vscode.Uri.file(source));
    if (!exe) {
      return comment + 'cc1 was not found. Set cc1.path, or run "cc1: Locate the Compiler".\n';
    }

    const out = cc1.scratchFile(cc1.assemblySuffix());
    const cwd = cc1.folderFor(vscode.Uri.file(source)) || path.dirname(source);
    const args = [source].concat(cc1.commonArgs(vscode.Uri.file(source)), ['-S', '-o', out]);
    this.output.appendLine('$ ' + exe + ' ' + args.join(' '));
    const result = await cc1.run(exe, args, cwd);

    if (result.code !== 0) {
      cc1.discard(out);
      const said = (result.stderr + result.stdout).trim() || 'cc1 exited ' + result.code;
      const header = comment + 'cc1 could not compile this file for ' +
        (cc1.effectiveTarget() || 'this machine') + '.\n' + comment + '\n';
      return header + said.split(/\r?\n/).map((l) => comment + l).join('\n') + '\n';
    }

    let text;
    try {
      text = fs.readFileSync(out, 'utf8');
    } catch (e) {
      text = comment + 'cc1 reported success but wrote nothing to ' + out + '\n';
    }
    cc1.discard(out);

    const banner = comment + path.basename(source) + '  ->  ' +
      (cc1.effectiveTarget() || 'host') +
      (cc1.effectiveTarget() === 'x86_64-windows' ? '  (' + cc1.config().get('masm', 'masm') + ')' : '') +
      '\n' + comment + 'generated by cc1 -S; this pane is read-only and refreshes with its source\n\n';
    return banner + text;
  }
}

module.exports = { AssemblyProvider, SCHEME };
